# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 08:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='ClusterRecsReviewQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='New position')),
                ('usefulness_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='This additional information useful for the choice of the most relevant property')),
                ('choice_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='This additional information makes the choice of the most relevant property difficult')),
            ],
            options={
                'verbose_name': 'Cluster QA',
                'verbose_name_plural': 'Cluster QAs',
            },
        ),
        migrations.CreateModel(
            name='HHUser',
            fields=[
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='user id')),
                ('cluster_id', models.IntegerField(unique=True, verbose_name='user cluster id')),
            ],
            options={
                'verbose_name': 'HH user',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='item id')),
                ('uri', models.CharField(max_length=200, null=True)),
                ('image_uri', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recs_type', models.CharField(choices=[('cb', 'Content-based'), ('cl', 'Cluster-based')], default='cl', max_length=2, verbose_name='Type of recommendations')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('cluster_qa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ClusterRecsReviewQA')),
                ('hh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HHUser', verbose_name='HH user')),
            ],
            options={
                'verbose_name': 'Recommendations review',
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='RecsReviewQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item position')),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('cluster_position', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quality_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='I liked the recommendations provided by the system')),
                ('diversity_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='The recommendations contained a lot of variety')),
                ('easiness_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='Selecting the best properties was easy')),
                ('happiness_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='I am happy with the properties I have chosen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
            options={
                'verbose_name': 'QA about recommendations',
                'verbose_name_plural': 'QAs about recommendations',
            },
        ),
        migrations.AddField(
            model_name='recsreview',
            name='qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RecsReviewQA'),
        ),
        migrations.AddField(
            model_name='recsreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clusterrecsreviewqa',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item', verbose_name='New item'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hh_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='main.HHUser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
