# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 16:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='HHUser',
            fields=[
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='user id')),
                ('cluster_id', models.IntegerField(unique=True, verbose_name='user cluster id')),
            ],
            options={
                'verbose_name': 'HH user',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HHUserRecsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', 'Answer 1'), ('2', 'Answer 2'), ('3', 'Answer 3'), ('4', 'Answer 4')], default='1', max_length=1, verbose_name='Review')),
                ('recs_type', models.CharField(choices=[('cb', 'Content-based'), ('cl', 'Cluster-based')], default='cl', max_length=2, verbose_name='Type of recommendations')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('hh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.HHUser')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HH user recommendations review',
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='item id')),
                ('uri', models.CharField(max_length=200, null=True)),
                ('image_uri', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecsClusterReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item cluster id')),
                ('cluster_pos', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cluster position')),
                ('item_pos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item position')),
                ('answer', models.CharField(choices=[('1', 'Answer 1'), ('2', 'Answer 2'), ('3', 'Answer 3'), ('4', 'Answer 4')], default='1', max_length=1, verbose_name='Review')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_review', to='main.HHUserRecsReview')),
            ],
            options={
                'verbose_name': 'Recommended cluster review',
                'ordering': ['-dt'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='hh_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='main.HHUser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
