# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:33
from __future__ import unicode_literals

import csv

import requests
from bs4 import BeautifulSoup
from django.conf import settings
from django.db import migrations


def get_existing_hh_items():
    req = requests.get("https://www.helpfulholidays.co.uk/api/keyword/search")
    data = req.json()

    items = {}

    for d in data.get("results", []):
        code = d.get("code")
        if code is not None:
            items[code] = {
                "uri": d["uri"],
                "name": d["name"]
            }
    return items


def get_dumped_hh_items():
    dumped_items = {}
    with open(settings.ITEM_CSV_PATH) as f:
        csv_reader = csv.reader(f)
        next(csv_reader)  # skipping header

        for row in csv_reader:
            if row:
                propcode, name = row[0], row[3]
                dumped_items[propcode] = name
    return dumped_items


def get_image_uri(item):
    url = settings.HH_URL + item.uri
    req = requests.get(url)

    soup = BeautifulSoup(req.text, "html.parser")
    imgs = soup.select("div#carousel img['data-index'='1']")

    image_uri = None
    if len(imgs) > 0:
        img_url = imgs[0].attrs['data-full-url']
        image_uri = img_url.replace(settings.HH_IMAGE_URL, "").strip()
    return image_uri


def populate_hh_items(apps, schema_editor):
    existing_items = get_existing_hh_items()
    dumped_items = get_dumped_hh_items()

    Item = apps.get_model('main', 'Item')

    for iid, name in dumped_items.items():
        d = existing_items.get(iid, {})
        item = Item(code=iid, uri=d.get("uri"), name=d.get("name", name))
        if item.uri is not None:
            item.image_uri = get_image_uri(item)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_hh_items),
    ]
