# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:29
from __future__ import unicode_literals

import csv
import requests

from django.conf import settings
from django.db import migrations


def get_existing_hh_items():
    req = requests.get("https://www.helpfulholidays.co.uk/api/keyword/search")
    data = req.json()

    items = {}

    for d in data.get("results", []):
        code = d.get("code")
        if code is not None:
            items[code] = {
                "uri": d["uri"],
                "name": d["name"]
            }
    return items


def get_dumped_hh_items(apps):
    HHUser = apps.get_model('main', 'HHUser')
    available_codes = set(HHUser.objects.values_list('code', flat=True))

    dumped_items = set()

    with open(settings.BOOKING_CSV_PATH) as f:
        csv_reader = csv.reader(f)
        next(csv_reader)  # skipping header

        for row in csv_reader:
            if row:
                code, propcode = row[0], row[4]
                if code in available_codes:
                    dumped_items.add(propcode)
    return dumped_items


def populate_hh_items(apps, schema_editor):
    existing_items_dict = get_existing_hh_items()
    dumped_items_set = get_dumped_hh_items(apps)

    Item = apps.get_model('main', 'Item')

    for iid in dumped_items_set:
        d = existing_items_dict.get(iid, {})
        item = Item(code=iid, uri=d.get("uri"), name=d.get("name"))
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_populate_hh_users'),
    ]

    operations = [
        migrations.RunPython(populate_hh_items),
    ]
