# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 07:20
from __future__ import unicode_literals

import requests
from bs4 import BeautifulSoup
from django.conf import settings
from django.db import migrations


def populate_items_images(apps, schema_editor):
    Item = apps.get_model('main', 'Item')

    for item in Item.objects.filter(uri__isnull=False):
        url = settings.HH_URL + item.uri
        req = requests.get(url)

        soup = BeautifulSoup(req.text, "html.parser")
        imgs = soup.select("div#carousel img['data-index'='1']")
        if len(imgs) > 0:
            img_url = imgs[0].attrs['data-full-url']
            item.image_uri = img_url.replace(settings.HH_IMAGE_URL, "").strip()
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_populate_hh_bookings'),
    ]

    operations = [
        migrations.RunPython(populate_items_images),
    ]
