# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:35
from __future__ import unicode_literals

import csv

from django.conf import settings
from django.db import migrations


def populate_bookings(apps, schema_editor):
    HHUser = apps.get_model('main', 'HHUser')
    Item = apps.get_model('main', 'Item')
    Booking = apps.get_model('main', 'Booking')

    available_codes = set(HHUser.objects.values_list('code', flat=True))
    available_propcodes = set(Item.objects.values_list('code', flat=True))

    with open(settings.BOOKING_CSV_PATH) as f:
        csv_reader = csv.reader(f)
        next(csv_reader)  # skipping header

        for row in csv_reader:
            if row:
                code, propcode, bookdate = row[0], row[4], row[5]
                if code in available_codes and propcode in available_propcodes:
                    booking = Booking(dt=bookdate)
                    booking.hh_user_id = code
                    booking.item_id = propcode
                    booking.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_populate_hh_users'),
    ]

    operations = [
        migrations.RunPython(populate_bookings),
    ]
