# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_populate_hh_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recs_type', models.CharField(choices=[('cb', 'Content-based'), ('cl', 'Cluster-based')], max_length=2, verbose_name='Type of recommendations')),
                ('hh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HHUser')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User evaluation case',
            },
        ),
    ]
