# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_populate_hh_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterrecsreviewqa',
            name='choice_qa',
            field=models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='It is easier to select the most relevant property knowing this additional information'),
        ),
        migrations.AlterField(
            model_name='clusterrecsreviewqa',
            name='usefulness_qa',
            field=models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='This information is useful for choosing the most relevant property'),
        ),
        migrations.AlterField(
            model_name='recsreview',
            name='hh_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HHUser', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='recsreviewqa',
            name='easiness_qa',
            field=models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='Selecting the best property was easy'),
        ),
        migrations.AlterField(
            model_name='recsreviewqa',
            name='happiness_qa',
            field=models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='I am happy with the property I have chosen'),
        ),
    ]
