# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_added_cluster_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterRecsReviewQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('cluster_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item position')),
                ('usefulness_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='This additional information useful for the choice of the most relevant property')),
                ('choice_qa', models.CharField(choices=[('sa', 'Strongly agree'), ('ag', 'Agree'), ('nt', 'Neutral'), ('dg', 'Disagree'), ('sd', 'Strongly disagree')], default=None, max_length=2, verbose_name='This additional information makes the choice of the most relevant property difficult')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
            options={
                'verbose_name': 'Cluster QA',
                'verbose_name_plural': 'Cluster QAs',
            },
        ),
        migrations.AddField(
            model_name='recsreview',
            name='cluster_qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ClusterRecsReviewQA'),
        ),
    ]
