# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_populate_items_image_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviewedHHUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('hh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HHUser')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
    ]
