# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userevalcase'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS main_userevalcase_view;"),
        migrations.RunSQL("""
            CREATE VIEW main_userevalcase_view 
            AS 
            SELECT 
                c.id,
                c.reviewer_id,
                c.hh_user_id, 
                c.recs_type,
                CASE WHEN r.id is NULL THEN 0 ELSE 1 END as is_reviewed
            FROM main_userevalcase c
                JOIN main_hhuser h ON c.hh_user_id = h.code
                LEFT JOIN  main_hhuserrecsreview r ON c.hh_user_id = r.hh_user_id 
                    AND c.reviewer_id = r.reviewer_id
                    AND c.recs_type = r.recs_type;
        """),
    ]
