# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userreviewedhhuser'),
    ]

    operations = [
        migrations.DeleteModel(name='ItemClusterReview'),
        migrations.DeleteModel(name='UserReviewedHHUser'),
    ]
