# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_userevalcase_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvalCaseView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recs_type', models.CharField(choices=[('cb', 'Content-based'), ('cl', 'Cluster-based')], max_length=2, verbose_name='Type of recommendations')),
                ('is_reviewed', models.BooleanField()),
            ],
            options={
                'db_table': 'main_userevalcase_view',
                'managed': False,
            },
        ),
    ]
