# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_old_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHUserRecsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', 'Answer 1'), ('2', 'Answer 2'), ('3', 'Answer 3'), ('4', 'Answer 4')], default='1', max_length=1, verbose_name='Review')),
                ('recs_type', models.CharField(choices=[('cb', 'Content-based'), ('cl', 'Cluster-based')], default='cl', max_length=2, verbose_name='Type of recommendations')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('hh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HHUser')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecsItemReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item position')),
                ('cluster_id', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item cluster id')),
                ('cluster_pos', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cluster position')),
                ('answer', models.CharField(choices=[('1', 'Answer 1'), ('2', 'Answer 2'), ('3', 'Answer 3'), ('4', 'Answer 4')], default='1', max_length=1, verbose_name='Review')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('user_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HHUserRecsReview')),
            ],
        ),
    ]
