# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hhuserrecsreview_recsitemreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hhuserrecsreview',
            name='hh_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.HHUser'),
        ),
    ]
