# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171106_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecsClusterReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item cluster id')),
                ('cluster_pos', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cluster position')),
                ('item_pos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Item position')),
                ('answer', models.CharField(choices=[('1', 'Answer 1'), ('2', 'Answer 2'), ('3', 'Answer 3'), ('4', 'Answer 4')], default='1', max_length=1, verbose_name='Review')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_review', to='main.HHUserRecsReview')),
            ],
        ),
        migrations.RemoveField(
            model_name='recsitemreview',
            name='item',
        ),
        migrations.RemoveField(
            model_name='recsitemreview',
            name='user_review',
        ),
        migrations.DeleteModel(
            name='RecsItemReview',
        ),
    ]
